version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped

    ports:
      - "27017:27017"  # MongoDB exposed on default port

    volumes:
      - mongo_data:/data/db  # Persistent database storage

    environment:
      - MONGO_INITDB_DATABASE=hate_speech_db

    # -----------------------------------------
    # AFTER STARTING THE CONTAINER:
    #
    # 1. Enter the container:
    #    docker exec -it mongodb bash
    #
    # 2. Open Mongo shell:
    #    mongosh
    #
    # 3. Switch to your database:
    #    use hate_speech_db
    #
    # 4. Verify collections:
    #    show collections
    #
    # This database stores:
    # - User posts
    # -----------------------------------------

volumes:
  mongo_data: